# Generated by Django 4.2.1 on 2025-02-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('locality', models.TextField(db_column='locality', primary_key=True, serialize=False)),
                ('fips', models.BigIntegerField(db_column='fips')),
                ('locality_mapping', models.TextField(db_column='locality_mapping')),
            ],
            options={
                'db_table': 'county_fips',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LocalSolarPolicyData',
        ),
        migrations.AlterModelTable(
            name='solarprojectdata',
            table='dev_solar_data_public',
        ),
    ]
