# Generated by Django 4.2.1 on 2025-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_countydata_delete_localsolarpolicydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('datapoint_term', models.TextField(db_column='datapoint_term', primary_key=True, serialize=False)),
                ('csv_term', models.TextField(db_column='csv_term')),
                ('working_definition', models.TextField(db_column='working_definition')),
                ('source_of_data', models.TextField(db_column='source_of_data')),
            ],
            options={
                'db_table': 'data_dictionary',
                'managed': False,
            },
        ),
    ]
