# Generated by Django 4.2.14 on 2026-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_datadictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageProjectData',
            fields=[
                ('data_id', models.TextField(blank=True, db_column='data_id', primary_key=True, serialize=False)),
                ('locality', models.TextField(blank=True, db_column='locality', null=True)),
                ('unit_of_government', models.TextField(blank=True, db_column='unit_of_government', null=True)),
                ('region', models.TextField(blank=True, db_column='region', null=True)),
                ('additional_localities', models.TextField(blank=True, db_column='additional_localities', null=True)),
                ('project_name', models.TextField(blank=True, db_column='project_name', null=True)),
                ('alt_names', models.TextField(blank=True, db_column='alt_names', null=True)),
                ('local_action_project_owner', models.TextField(blank=True, db_column='local_action_project_owner', null=True)),
                ('project_bess_mw', models.FloatField(blank=True, db_column='project_bess_mw', null=True)),
                ('project_bess_capacity', models.FloatField(blank=True, db_column='project_bess_capacity', null=True)),
                ('bess_duration_short_long', models.TextField(blank=True, db_column='bess_duration_short_long', null=True)),
                ('local_permit_status', models.TextField(blank=True, db_column='local_permit_status', null=True)),
                ('location_description', models.TextField(blank=True, db_column='location_description', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='longitude', null=True)),
                ('cocolation_info', models.TextField(blank=True, db_column='colocation_info', null=True)),
                ('solar_storage', models.TextField(blank=True, db_column='solar_storage', null=True)),
                ('project_type', models.TextField(blank=True, db_column='project_type', null=True)),
                ('storage_tech', models.TextField(blank=True, db_column='storage_tech', null=True)),
                ('storage_chemistry', models.TextField(blank=True, db_column='storage_chemistry', null=True)),
                ('public_bess_project_acres', models.FloatField(blank=True, db_column='public_bess_project_acres', null=True)),
                ('final_action_date', models.TextField(blank=True, db_column='final_action_date', null=True)),
                ('final_action_year', models.TextField(blank=True, db_column='final_action_year', null=True)),
                ('siting_agreement_exists', models.TextField(blank=True, db_column='siting_agreement_exists', null=True)),
                ('siting_agreement_date', models.TextField(blank=True, db_column='siting_agreement_date', null=True)),
                ('siting_agreement_link', models.TextField(blank=True, db_column='siting_agreement_link', null=True)),
                ('pjm_queue_number', models.TextField(blank=True, db_column='pjm_queue_number', null=True)),
                ('deq_permit_number', models.TextField(blank=True, db_column='deq_permit_number', null=True)),
                ('eia_plant_id', models.BigIntegerField(blank=True, db_column='eia_plant_id', null=True)),
                ('eia_generator_id', models.BigIntegerField(blank=True, db_column='eia_generator_id', null=True)),
                ('eia_operating_status', models.TextField(blank=True, db_column='eia_operating_status', null=True)),
                ('eia_project_status', models.TextField(blank=True, db_column='eia_project_status', null=True)),
                ('eia_operating_year', models.TextField(blank=True, db_column='eia_operating_year', null=True)),
            ],
            options={
                'db_table': 'dev_storage_data_public',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='countydata',
            table='county_fips_new',
        ),
    ]
